spring.application.name=studentapp

spring.datasource.url=jdbc:mysql://host.docker.internal:3308/studentdb
spring.datasource.username=root
spring.datasource.password=Dhiva@2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false